---

package_list__fedora_k8s:
  #- kubernetes
  - kubernetes-client
  - kind
  - helm
  - opentofu
  - docker-cli
  - docker-compose
  - podman
  #- podman-docker
  #- podman-compose
  - buildah
  - skopeo

go_packages__fedora_k8s:
  #- golang.stackrox.io/kube-linter/cmd/kube-linter
  - github.com/kubecolor/kubecolor

user_groups__fedora_k8s:
  - docker
